import {Activity,ArrowRight,Boxes,Clock3,FolderPlus,Gauge,HardDrive,Mic2,Video} from "lucide-react";
import {EmptyState} from "@/components/EmptyState";
import {PageHeader} from "@/components/PageHeader";
import {useI18n} from "@/i18n";
import type {EngineRecord,JobRecord,ProjectRecord,RuntimeStatus} from "@/types";

type Props={projects:ProjectRecord[];engines:EngineRecord[];jobs:JobRecord[];runtime:RuntimeStatus|null;onImport:()=>void;onOpenProject:(project:ProjectRecord)=>void;onNavigate:(section:"projects"|"engines")=>void};
export function DashboardPage({projects,engines,jobs,runtime,onImport,onOpenProject,onNavigate}:Props){
  const{t,date}=useI18n();const ready=engines.filter(engine=>engine.installation.status==="ready").length;const running=jobs.filter(job=>["queued","running"].includes(job.status)).length;
  return <div className="h-full overflow-auto">
    <PageHeader kicker={t("dashboard.kicker")} title={t("dashboard.title")} description={t("dashboard.description")} actions={<button className="ui-button ui-button-primary" onClick={onImport}><Video/>{t("dashboard.import")}</button>}/>
    <div className="mx-auto grid max-w-[1500px] gap-5 p-8">
      <section className="grid grid-cols-[minmax(340px,1.4fr)_minmax(520px,2fr)] gap-4">
        <button className="group ui-panel flex min-h-36 items-center gap-5 p-6 text-left hover:border-accent/60" onClick={onImport}><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-accent text-white shadow-[0_10px_30px_rgba(201,133,84,.2)]"><FolderPlus className="size-5"/></span><span className="min-w-0 flex-1"><small className="ui-kicker">{t("dashboard.newSession")}</small><strong className="mt-1 block text-[18px] font-semibold text-foreground">{t("dashboard.createVideo")}</strong><p className="mt-1 text-[12px] text-copy">{t("dashboard.sourceSafe")}</p></span><ArrowRight className="size-5 text-muted transition-transform group-hover:translate-x-1"/></button>
        <div className="ui-panel grid grid-cols-3 divide-x divide-line p-2"><Metric icon={HardDrive} label={t("dashboard.storage")} value={runtime?formatBytes(runtime.hardware.memory?.available_bytes||0):"—"} note={t("dashboard.memoryAvailable")}/><Metric icon={Boxes} label={t("dashboard.engines")} value={`${ready}/${engines.length}`} note={t("dashboard.locallyValidated")}/><Metric icon={Clock3} label={t("dashboard.activeQueue")} value={String(running)} note={t("dashboard.operationRunning")}/></div>
      </section>
      <section className="ui-panel overflow-hidden"><header className="flex items-center justify-between border-b border-line px-5 py-4"><div><span className="ui-kicker">{t("dashboard.latest")}</span><h2 className="mt-1 text-[16px] font-semibold">{t("dashboard.resume")}</h2></div><button className="ui-button" onClick={()=>onNavigate("projects")}>{t("dashboard.allProjects")}<ArrowRight/></button></header>
        {projects.length===0?<div className="p-5"><EmptyState icon={Mic2} title={t("dashboard.empty")} description={t("dashboard.emptyBody")} action={<button className="ui-button" onClick={onImport}>{t("dashboard.import")}</button>}/></div>:<div className="grid grid-cols-2 gap-px bg-line xl:grid-cols-4">{projects.slice(0,4).map(project=><button className="group min-h-36 bg-surface p-5 text-left hover:bg-raised" key={project.id} onClick={()=>onOpenProject(project)}><div className="flex items-start justify-between"><span className="grid size-9 place-items-center rounded-lg border border-line bg-canvas font-mono text-[11px] font-bold text-accent">{project.name.slice(0,2).toUpperCase()}</span><ArrowRight className="size-4 text-muted transition-transform group-hover:translate-x-1"/></div><strong className="mt-4 block truncate text-[13px]">{project.name}</strong><span className="mt-1 block text-[11px] text-muted">{project.source_language||t("common.auto")} → {project.target_language||t("common.undefined")}</span><span className="mt-3 block text-[10px] text-copy">{date(project.updated_at,{dateStyle:"medium"})}</span></button>)}</div>}
      </section>
      <section className="grid grid-cols-2 gap-4"><button className="ui-panel group flex min-h-28 items-center gap-4 p-5 text-left hover:border-accent/50" onClick={()=>onNavigate("engines")}><span className="grid size-10 place-items-center rounded-lg bg-accent/10 text-accent"><Boxes/></span><span className="flex-1"><small className="ui-kicker">{t("dashboard.catalog")}</small><strong className="mt-1 block text-[14px]">{t("dashboard.prepare")}</strong><p className="mt-1 text-[11px] text-copy">{t("dashboard.prepareBody")}</p></span><ArrowRight className="text-muted group-hover:text-accent"/></button><article className="ui-panel flex min-h-28 items-center gap-4 p-5"><span className={`grid size-10 place-items-center rounded-lg ${running?"bg-success/10 text-success":"bg-raised text-muted"}`}>{running?<Activity className="animate-pulse"/>:<Gauge/>}</span><span><small className="ui-kicker">{t("activity.title")}</small><strong className="mt-1 block text-[14px]">{running?t("activity.runningCount",{count:running}):t("activity.empty")}</strong><p className="mt-1 text-[11px] text-copy">{t("activity.background")}</p></span></article></section>
    </div>
  </div>;
}
function Metric({icon:Icon,label,value,note}:{icon:typeof HardDrive;label:string;value:string;note:string}){return <div className="flex min-w-0 items-center gap-3 px-5"><Icon className="size-4 shrink-0 text-muted"/><span className="min-w-0"><small className="ui-kicker block truncate">{label}</small><strong className="mt-1 block text-[19px] font-semibold tracking-tight">{value}</strong><em className="block truncate text-[10px] not-italic text-muted">{note}</em></span></div>}
function formatBytes(value:number){return value?`${(value/1024**3).toFixed(1)} GB`:"—"}
