import {useState} from "react";
import {Copy,Database,FolderCog,Gauge,Globe2,KeyRound,MonitorCog,Palette,RotateCcw,ShieldCheck,SlidersHorizontal} from "lucide-react";
import {PageHeader} from "@/components/PageHeader";
import {languages,useI18n,type Locale} from "@/i18n";
import {appearance,applyAppearance,type DensityId,type ThemeId} from "@/lib/appearance";
import type {AppConfig,RuntimeStatus} from "@/types";
type Section="storage"|"performance"|"providers"|"media"|"appearance"|"diagnostics";
const themes:ThemeId[]=["graphite","oled","warm","light"];const densities:DensityId[]=["compact","comfortable","spacious"];
export function SettingsPage({config,runtime}:{config:AppConfig|null;runtime:RuntimeStatus|null}){
  const{t,locale,setLocale}=useI18n();const[section,setSection]=useState<Section>("storage");const[look,setLook]=useState(appearance);const[performanceMode,setPerformanceMode]=useState(()=>localStorage.getItem("dubroom.performanceProfile")||"auto");
  const setPerformance=(mode:string)=>{localStorage.setItem("dubroom.performanceProfile",mode);setPerformanceMode(mode);window.dispatchEvent(new Event("dubroom:performance"))};const setAppearance=(patch:Partial<typeof look>)=>{const next={...look,...patch};setLook(next);applyAppearance(next.theme,next.density,next.reducedMotion)};
  const navigation:[Section,typeof FolderCog,string][]=[["storage",FolderCog,"settings.storage"],["performance",Gauge,"settings.performance"],["providers",KeyRound,"settings.providers"],["media",SlidersHorizontal,"settings.media"],["appearance",Palette,"settings.appearance"],["diagnostics",MonitorCog,"settings.diagnostics"]];
  return <div className="flex h-full min-h-0 flex-col overflow-hidden"><PageHeader kicker={t("settings.kicker")} title={t("settings.title")} description={t("settings.description")}/><div className="grid min-h-0 flex-1 grid-cols-[220px_minmax(0,1fr)]">
    <nav data-testid="settings-tabs" className="border-r border-line p-4">{navigation.map(([id,Icon,key])=><button key={id} className={`mb-1 flex h-10 w-full items-center gap-3 rounded-lg px-3 text-[12px] transition-colors ${section===id?"bg-raised text-foreground":"text-muted hover:bg-surface hover:text-copy"}`} onClick={()=>setSection(id)}><Icon className={`size-4 ${section===id?"text-accent":""}`}/>{t(key)}</button>)}</nav>
    <section className="min-h-0 overflow-auto p-8"><div className="mx-auto max-w-4xl">
      {section==="storage"&&<><Head icon={Database} title={t("settings.storageTitle")} body={t("settings.storageBody")}/><div className="grid gap-2">{Object.entries(config?.paths||{}).map(([key,value])=><div key={key} className="ui-panel flex min-w-0 items-center gap-4 px-4 py-3"><span className="w-28 shrink-0 text-[10px] font-semibold uppercase tracking-[.12em] text-muted">{key}</span><code className="min-w-0 flex-1 truncate text-[11px] text-copy" title={value}>{value}</code><button className="ui-icon-button" onClick={()=>void navigator.clipboard.writeText(value)}><Copy/></button></div>)}</div><Note title={t("settings.localData")} body={t("settings.localDataBody")}/></>}
      {section==="performance"&&<><Head icon={Gauge} title={t("settings.performanceTitle")} body={t("settings.performanceBody")}/><div className="grid grid-cols-2 gap-2">{["auto","fluid","balanced","economy"].map(mode=><button key={mode} className={`ui-panel flex items-start gap-3 p-4 text-left ${performanceMode===mode?"border-accent bg-accent/5":""}`} onClick={()=>setPerformance(mode)}><Gauge className={performanceMode===mode?"text-accent":"text-muted"}/><span><strong className="block text-[12px]">{t(`performance.${mode}`)}</strong><small className="mt-1 block text-[10px] leading-4 text-muted">{t(`performance.${mode}Body`)}</small></span></button>)}</div><div className="mt-5 grid grid-cols-4 gap-2"><Metric label={t("settings.processor")} value={runtime?.hardware.cpu||"—"}/><Metric label={t("settings.cpuThreads")} value={String(runtime?.hardware.cpu_threads||"—")}/><Metric label={t("settings.acceleration")} value={runtime?.hardware.cuda?.name||"CPU"}/><Metric label={t("settings.freeMemory")} value={formatBytes(runtime?.hardware.memory?.available_bytes)}/></div></>}
      {section==="providers"&&<><Head icon={KeyRound} title={t("settings.providersTitle")} body={t("settings.providersBody")}/><div className="ui-panel grid min-h-56 place-items-center p-8 text-center"><div><KeyRound className="mx-auto size-7 text-muted"/><strong className="mt-4 block text-[13px]">{t("settings.noProvider")}</strong><p className="mt-1 text-[11px] text-muted">{t("settings.secretBody")}</p></div></div></>}
      {section==="media"&&<><Head icon={SlidersHorizontal} title={t("settings.mediaTitle")} body={t("settings.mediaBody")}/><div className="ui-panel divide-y divide-line"><Setting label={t("settings.videoExport")} help={t("settings.videoExportBody")}><select className="ui-input w-52" defaultValue="copy"><option value="copy">{t("settings.copyVideo")}</option><option value="encode">{t("settings.reencode")}</option></select></Setting><Setting label={t("settings.voiceNormalize")} help={t("settings.voiceNormalizeBody")}><input type="checkbox" defaultChecked className="size-4 accent-[var(--accent)]"/></Setting></div></>}
      {section==="appearance"&&<><Head icon={Palette} title={t("settings.appearanceTitle")} body={t("settings.appearanceBody")}/><div className="grid gap-6"><Setting label={t("settings.interfaceLanguage")} help=""><Globe2 className="size-4 text-muted"/><select className="ui-input w-52" value={locale} onChange={event=>setLocale(event.target.value as Locale)}>{languages.map(language=><option key={language.id} value={language.id}>{language.native}</option>)}</select></Setting><div><span className="ui-label">{t("settings.theme")}</span><div className="mt-2 grid grid-cols-4 gap-2">{themes.map(theme=><button key={theme} className={`ui-panel p-3 text-left ${look.theme===theme?"border-accent":""}`} onClick={()=>setAppearance({theme})}><i className={`mb-3 block h-8 rounded-md border border-line ${themeSwatches[theme]}`}/><strong className="text-[11px]">{t(`theme.${theme}`)}</strong></button>)}</div></div><div><span className="ui-label">{t("settings.density")}</span><div className="mt-2 grid grid-cols-3 gap-2">{densities.map(density=><button key={density} className={`ui-button ${look.density===density?"border-accent text-accent":""}`} onClick={()=>setAppearance({density})}>{t(`density.${density}`)}</button>)}</div></div><Setting label={t("motion.reduce")} help={t("settings.motionBody")}><input type="checkbox" checked={look.reducedMotion} onChange={event=>setAppearance({reducedMotion:event.target.checked})} className="size-4 accent-[var(--accent)]"/></Setting><button className="ui-button w-fit" onClick={()=>{localStorage.removeItem("dubroom.onboardingComplete");window.location.reload()}}><RotateCcw/>{t("settings.restartOnboarding")}</button></div></>}
      {section==="diagnostics"&&<><Head icon={MonitorCog} title={t("settings.diagnosticsTitle")} body={t("settings.diagnosticsBody")}/><div className="grid grid-cols-4 gap-2"><Metric label="Python" value={runtime?.hardware.python||"—"}/><Metric label="FFmpeg" value={t(runtime?.tools.ffmpeg?"settings.available":"settings.absent")}/><Metric label="FFprobe" value={t(runtime?.tools.ffprobe?"settings.available":"settings.absent")}/><Metric label="NVIDIA" value={t(runtime?.tools.nvidia_smi?"settings.available":"settings.absent")}/></div><div className="ui-panel mt-4 p-4"><span className="ui-label">{t("settings.workspace")}</span><code className="mt-2 block truncate text-[11px] text-copy">{runtime?.workspace_root||"—"}</code></div></>}
    </div></section></div></div>;
}
const themeSwatches:Record<ThemeId,string>={graphite:"bg-[#111419]",oled:"bg-black",warm:"bg-[#1d1915]",light:"bg-[#eeece7]"};
function Head({icon:Icon,title,body}:{icon:typeof Database;title:string;body:string}){return <header className="mb-6 flex items-start gap-4"><span className="grid size-10 place-items-center rounded-lg border border-line bg-raised text-accent"><Icon/></span><div><h2 className="text-[18px] font-semibold">{title}</h2><p className="mt-1 text-[11px] text-copy">{body}</p></div></header>}
function Metric({label,value}:{label:string;value:string}){return <span className="ui-panel min-w-0 p-3"><small className="ui-label block truncate">{label}</small><strong className="mt-2 block truncate text-[12px]">{value}</strong></span>}
function Setting({label,help,children}:{label:string;help:string;children:React.ReactNode}){return <label className="flex min-h-16 items-center gap-3 px-4"><span className="flex-1"><strong className="block text-[12px]">{label}</strong>{help&&<small className="mt-1 block text-[10px] text-muted">{help}</small>}</span>{children}</label>}
function Note({title,body}:{title:string;body:string}){return <div className="mt-5 flex gap-3 rounded-lg border border-success/25 bg-success/5 p-4"><ShieldCheck className="size-4 text-success"/><span><strong className="block text-[12px]">{title}</strong><p className="mt-1 text-[10px] text-copy">{body}</p></span></div>}
function formatBytes(value?:number|null){return value?`${(value/1024**3).toFixed(1)} GB`:"—"}
