import {useEffect,useMemo,useRef,useState} from "react";
import {AlertTriangle,Clipboard,CloudDownload,FileAudio,LoaderCircle,Mic,Plus,Search,ShieldCheck,Square,Upload,X,Youtube} from "lucide-react";
import {api} from "@/lib/api";
import {useI18n} from "@/i18n";
import type {TtsModel,TtsPresetVoice,TtsProfileInput,YouTubeDownload,YouTubeInfo} from "@/types";
import {formatTimecode,YouTubeRangeSelector,validateYouTubeRange} from "@/components/YouTubeRangeSelector";
import type {YouTubeRangeMode} from "@/components/YouTubeRangeSelector";
type Props={onClose:()=>void;onCreated:()=>Promise<void>;models:TtsModel[];initialType?:TtsProfileInput["voice_type"];preferredEngineId?:string|null};
export function ProfileCreator({onClose,onCreated,models,initialType="preset",preferredEngineId=null}:Props){
  const{t,locale}=useI18n();const[form,setForm]=useState<TtsProfileInput>({name:"",language:locale,voice_type:initialType,preset_engine:null,default_engine:preferredEngineId,gender:"unspecified",age_group:"adult",primary_role:"other",roles:[],usage_scope:"both"});const[presets,setPresets]=useState<TtsPresetVoice[]>([]);const[samplePath,setSamplePath]=useState("");const[referenceText,setReferenceText]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[recording,setRecording]=useState(false);const[recordingUrl,setRecordingUrl]=useState("");const[recordingData,setRecordingData]=useState("");const[recordingSeconds,setRecordingSeconds]=useState(0);const recorder=useRef<MediaRecorder|null>(null);const timer=useRef<ReturnType<typeof setInterval>|null>(null);
  const modelOptions=useMemo(()=>models.filter(model=>model.voice_modes?.includes(form.voice_type)&&(!model.languages?.length||model.languages.includes(form.language))),[models,form.voice_type,form.language]);
  const selectedModel=modelOptions.find(model=>model.id===form.default_engine);
  useEffect(()=>{if(selectedModel?.downloaded)return;const fallback=modelOptions.find(model=>model.downloaded);setForm(current=>({...current,default_engine:fallback?.id||null,preset_engine:form.voice_type==="preset"?fallback?.engine||null:null,preset_voice_id:null}))},[modelOptions,selectedModel?.downloaded,form.voice_type]);
  useEffect(()=>{if(form.voice_type!=="preset"||!form.preset_engine){setPresets([]);return}api.ttsPresets(form.preset_engine).then(voices=>{const compatible=form.preset_engine==="kokoro"?voices.filter(voice=>voice.language===form.language||voice.language==="multi"):voices;setPresets(compatible);setForm(current=>({...current,preset_voice_id:compatible.some(voice=>voice.voice_id===current.preset_voice_id)?current.preset_voice_id:compatible[0]?.voice_id||null}))}).catch(reason=>setError(reason.message))},[form.voice_type,form.preset_engine,form.language]);
  useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);if(recordingUrl)URL.revokeObjectURL(recordingUrl);recorder.current?.stream.getTracks().forEach(track=>track.stop())},[recordingUrl]);
  const chooseSample=async()=>{const path=await window.dubStudio?.openAudio();if(path){setSamplePath(path);setRecordingData("");setRecordingUrl("")}};
  const startRecording=async()=>{try{setError("");const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const chunks:Blob[]=[];const mediaRecorder=new MediaRecorder(stream);recorder.current=mediaRecorder;mediaRecorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};mediaRecorder.onstop=()=>{const blob=new Blob(chunks,{type:mediaRecorder.mimeType||"audio/webm"});setRecordingUrl(URL.createObjectURL(blob));const reader=new FileReader();reader.onload=()=>setRecordingData(String(reader.result||""));reader.readAsDataURL(blob);stream.getTracks().forEach(track=>track.stop())};mediaRecorder.start(250);setRecordingSeconds(0);setRecording(true);timer.current=setInterval(()=>setRecordingSeconds(value=>value+1),1000)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}};
  const stopRecording=()=>{recorder.current?.stop();setRecording(false);if(timer.current)clearInterval(timer.current);timer.current=null};
  const save=async()=>{if(!form.name.trim()){setError(t("profile.nameError"));return}if(form.voice_type==="cloned"&&!samplePath&&!recordingData){setError(t("profile.sampleRequired"));return}setBusy(true);setError("");try{const profile=await api.createTtsProfile(form);if(form.voice_type==="cloned"){if(recordingData)await api.addTtsRecordingSample(profile.id,recordingData,referenceText.trim());else await api.addTtsSample(profile.id,samplePath,referenceText.trim())}await onCreated()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
  const modeReady=(type:TtsProfileInput["voice_type"])=>models.some(model=>model.downloaded&&model.voice_modes?.includes(type));
  return <div className="fixed inset-0 z-[100] flex justify-end bg-black/60 backdrop-blur-sm" onMouseDown={onClose}><aside className="grid h-full w-[560px] grid-rows-[64px_minmax(0,1fr)_64px] border-l border-line bg-surface shadow-2xl" onMouseDown={event=>event.stopPropagation()}><header className="flex items-center justify-between border-b border-line px-5"><div><span className="ui-kicker">{t("profile.workspace")}</span><h2 className="mt-1 text-[16px] font-semibold">{t("profile.new")}</h2></div><button className="ui-icon-button" onClick={onClose}><X/></button></header><section className="min-h-0 overflow-auto p-5"><div className="grid gap-4"><div className="grid grid-cols-2 gap-3"><Field label={t("profile.name")}><input autoFocus className="ui-input" value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder={t("profile.namePlaceholder")}/></Field><Field label={t("profile.language")}><select className="ui-input" value={form.language} onChange={event=>setForm({...form,language:event.target.value})}>{["fr","en","es","pt","de","ja","ko","zh","ar","it"].map(language=><option key={language} value={language}>{language.toUpperCase()}</option>)}</select></Field></div><CastingIdentity form={form} onChange={setForm}/><Field label={t("profile.type")}><div className="grid grid-cols-3 gap-1 rounded-lg border border-line bg-canvas p-1">{(["preset","cloned","designed"] as const).map(type=><button key={type} disabled={!modeReady(type)} className={`rounded-md px-2 py-2 text-[10px] disabled:cursor-not-allowed disabled:opacity-35 ${form.voice_type===type?"bg-raised text-foreground":"text-muted"}`} onClick={()=>setForm({...form,voice_type:type,preset_engine:null,preset_voice_id:null,default_engine:null})}>{t(type==="cloned"?"profile.clone":type==="designed"?"profile.designed":"profile.preset")}</button>)}</div></Field>
    <Field label={t("profile.engine")}><select className="ui-input" value={form.default_engine||""} onChange={event=>{const model=models.find(item=>item.id===event.target.value);setForm({...form,default_engine:model?.id||null,preset_engine:form.voice_type==="preset"?model?.engine||null:null,preset_voice_id:null})}}>{modelOptions.map(model=><option key={model.id} value={model.id} disabled={!model.downloaded}>{model.display_name} · {model.downloaded?t("common.ready"):t("common.notInstalled")}</option>)}</select></Field>
    {selectedModel&&<div className="flex flex-wrap gap-2 rounded-lg border border-line bg-canvas/70 p-3 text-[10px] text-muted"><span className="ui-chip">{selectedModel.tier||"local"}</span><span>{selectedModel.model_size||selectedModel.family}</span><span>{selectedModel.sample_rate?`${selectedModel.sample_rate/1000} kHz`:""}</span><span>{selectedModel.recommended_vram_gb?`${selectedModel.recommended_vram_gb} GB VRAM`:"CPU/GPU"}</span></div>}
    {form.voice_type==="preset"&&<Field label={t("profile.voice")}><select className="ui-input" value={form.preset_voice_id||""} onChange={event=>setForm({...form,preset_voice_id:event.target.value})}>{presets.map(voice=><option key={voice.voice_id} value={voice.voice_id}>{voice.name} · {voice.language?.toUpperCase()} · {voice.gender||"—"}</option>)}</select></Field>}
    {form.voice_type==="designed"&&<Field label={t("profile.description")}><textarea className="ui-input min-h-28" value={form.design_prompt||""} onChange={event=>setForm({...form,design_prompt:event.target.value})} placeholder={t("profile.descriptionPlaceholder")}/></Field>}
    {form.voice_type==="cloned"&&<div className="grid gap-3"><div className="flex gap-2 rounded-lg border border-success/25 bg-success/5 p-3 text-[10px] text-copy"><ShieldCheck className="size-4 text-success"/>{t("profile.cloneWarning")}</div><div className={`ui-panel p-5 text-center ${recording?"border-danger":""}`}><div className="mx-auto mb-4 flex h-12 items-center justify-center gap-1">{Array.from({length:30},(_,index)=><i key={index} className={`w-0.5 rounded ${recording?"animate-pulse bg-danger":"bg-accent/50"}`} style={{height:8+((index*11)%36)}}/>)}</div><strong className="text-[12px]">{recording?t("profile.recording"):recordingUrl?t("profile.captureReady"):t("profile.capturePrompt")}</strong><small className="mt-1 block text-[10px] text-muted">{recording?formatTime(recordingSeconds):t("profile.captureBody")}</small><div className="mt-4 flex justify-center gap-2">{recording?<button className="ui-button border-danger text-danger" onClick={stopRecording}><Square/>{t("profile.stop")}</button>:<button className="ui-button" onClick={()=>void startRecording()}><Mic/>{t("profile.record")}</button>}<button className="ui-button" onClick={()=>void chooseSample()}><Upload/>{t("profile.importSample")}</button></div>{recordingUrl&&<audio className="mt-4 h-9 w-full" src={recordingUrl} controls/>}</div><YouTubeVoiceSample onReady={path=>{setSamplePath(path);setRecordingData("");setRecordingUrl("")}}/>{samplePath&&<div className="flex items-center gap-2 rounded-lg border border-line bg-raised p-3 text-[10px]"><FileAudio className="size-4 text-accent"/><span className="truncate">{samplePath.split(/[\\/]/).pop()}</span></div>}<Field label={t("profile.referencePrompt")}><textarea className="ui-input min-h-24" value={referenceText} onChange={event=>setReferenceText(event.target.value)} placeholder={t("profile.referencePlaceholder")}/><small className="text-[9px] leading-4 text-muted">{t("profile.autoTranscript")}</small></Field></div>}
    <Field label={t("profile.personality")}><textarea className="ui-input min-h-20" value={form.personality||""} onChange={event=>setForm({...form,personality:event.target.value})} placeholder={t("profile.personalityPlaceholder")}/></Field>{error&&<div className="flex gap-2 rounded-lg bg-danger/10 p-3 text-[10px] text-danger"><AlertTriangle className="size-4"/>{error}</div>}</div></section><footer className="flex items-center justify-end gap-2 border-t border-line px-5"><button className="ui-button" onClick={onClose}>{t("profile.cancel")}</button><button className="ui-button ui-button-primary" disabled={busy||recording||!form.name.trim()||!selectedModel?.downloaded||(form.voice_type==="preset"&&!form.preset_voice_id)} onClick={()=>void save()}>{busy?<LoaderCircle className="animate-spin"/>:<Plus/>}{t("profile.create")}</button></footer></aside></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5"><span className="ui-label">{label}</span>{children}</label>}
function formatTime(seconds:number){return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
const genders:TtsProfileInput["gender"][]=["female","male","neutral","unspecified"];
const ageGroups:TtsProfileInput["age_group"][]=["child","teen","young_adult","adult","senior","unspecified"];
const castingRoles:TtsProfileInput["primary_role"][]=["mc","female_lead","narrator","antagonist","supporting","child","background","other"];
const usageScopes:TtsProfileInput["usage_scope"][]=["both","single","multi"];
function CastingIdentity({form,onChange}:{form:TtsProfileInput;onChange:(next:TtsProfileInput)=>void}){const{t}=useI18n();return <section className="rounded-xl border border-line bg-canvas/60 p-3"><div className="mb-3"><span className="ui-kicker">{t("profile.castingIdentity")}</span><p className="mt-1 text-[9px] leading-4 text-muted">{t("profile.castingIdentityBody")}</p></div><div className="grid grid-cols-2 gap-3"><Field label={t("profile.gender")}><select className="ui-input" value={form.gender} onChange={event=>onChange({...form,gender:event.target.value as TtsProfileInput["gender"]})}>{genders.map(value=><option key={value} value={value}>{t(`profile.gender.${value}`)}</option>)}</select></Field><Field label={t("profile.ageGroup")}><select className="ui-input" value={form.age_group} onChange={event=>onChange({...form,age_group:event.target.value as TtsProfileInput["age_group"]})}>{ageGroups.map(value=><option key={value} value={value}>{t(`profile.ageGroup.${value}`)}</option>)}</select></Field><Field label={t("profile.primaryRole")}><select className="ui-input" value={form.primary_role} onChange={event=>onChange({...form,primary_role:event.target.value as TtsProfileInput["primary_role"],roles:event.target.value==="other"?[]:[event.target.value]})}>{castingRoles.map(value=><option key={value} value={value}>{t(`profile.role.${value}`)}</option>)}</select></Field><Field label={t("profile.usageScope")}><select className="ui-input" value={form.usage_scope} onChange={event=>onChange({...form,usage_scope:event.target.value as TtsProfileInput["usage_scope"]})}>{usageScopes.map(value=><option key={value} value={value}>{t(`profile.usage.${value}`)}</option>)}</select></Field></div></section>}

function YouTubeVoiceSample({onReady}:{onReady:(path:string)=>void}){
  const{t}=useI18n();
  const[url,setUrl]=useState("");
  const[info,setInfo]=useState<YouTubeInfo|null>(null);
  const[download,setDownload]=useState<YouTubeDownload|null>(null);
  const[mode,setMode]=useState<YouTubeRangeMode>("excerpt");
  const[start,setStart]=useState("00:00");
  const[end,setEnd]=useState("00:15");
  const[busy,setBusy]=useState(false);
  const[error,setError]=useState("");
  const active=Boolean(download&&["queued","downloading","processing"].includes(download.status));

  useEffect(()=>{
    if(!download||!["queued","downloading","processing"].includes(download.status))return;
    let alive=true;
    const timer=setInterval(()=>api.youtubeDownload(download.id).then(next=>{
      if(!alive)return;
      setDownload(next);
      if(next.status==="completed"&&next.path){setBusy(false);onReady(next.path)}
      if(next.status==="failed"){setBusy(false);setError(next.error||next.message)}
      if(next.status==="cancelled")setBusy(false);
    }).catch(reason=>alive&&setError(reason instanceof Error?reason.message:String(reason))),800);
    return()=>{alive=false;clearInterval(timer)};
  },[download?.id,download?.status,onReady]);

  const inspect=async()=>{
    if(!url.trim())return;
    setBusy(true);setError("");
    try{
      const next=await api.inspectYouTube(url.trim());
      setInfo(next);setStart("00:00");setEnd(formatTimecode(Math.min(next.duration||15,15)));
    }catch(reason){setInfo(null);setError(reason instanceof Error?reason.message:String(reason))}
    finally{setBusy(false)}
  };
  const paste=async()=>{try{setUrl(await navigator.clipboard.readText());setInfo(null);setError("")}catch{setError(t("import.clipboardDenied"))}};
  const downloadAudio=async()=>{
    if(!info)return;
    const range=validateYouTubeRange(mode,start,end,info.duration);
    if(!range.valid){setError(t("youtubeRange.invalid"));return}
    setBusy(true);setError("");
    try{setDownload(await api.startYouTubeDownload(info.webpage_url,info.title,{mediaType:"audio",startSeconds:range.startSeconds,endSeconds:range.endSeconds}))}
    catch(reason){setBusy(false);setError(reason instanceof Error?reason.message:String(reason))}
  };

  return <section className="rounded-xl border border-line bg-canvas/50 p-4">
    <div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-danger/10 text-danger"><Youtube className="size-4"/></span><div><strong className="text-[11px]">{t("profile.youtubeSample")}</strong><p className="mt-1 text-[9px] leading-4 text-muted">{t("profile.youtubeSampleBody")}</p></div></div>
    {!active&&<div className="mt-3 flex gap-2"><input className="ui-input min-w-0 flex-1" value={url} onChange={event=>{setUrl(event.target.value);setInfo(null);setError("")}} onKeyDown={event=>event.key==="Enter"&&void inspect()} placeholder="https://youtu.be/…"/><button type="button" className="ui-icon-button" title={t("import.paste")} onClick={()=>void paste()}><Clipboard/></button><button type="button" className="ui-button" disabled={busy||!url.trim()} onClick={()=>void inspect()}>{busy?<LoaderCircle className="animate-spin"/>:<Search/>}{t("import.inspect")}</button></div>}
    {info&&!active&&<div className="mt-3 grid gap-3"><div className="rounded-lg border border-line bg-raised p-3"><small className="ui-kicker">{info.channel||"YouTube"} · {formatTimecode(info.duration||0)}</small><strong className="mt-1 line-clamp-2 block text-[11px]">{info.title}</strong></div><YouTubeRangeSelector compact duration={info.duration} mode={mode} start={start} end={end} onMode={setMode} onStart={setStart} onEnd={setEnd}/><button type="button" className="ui-button ui-button-primary justify-center" disabled={busy||info.live} onClick={()=>void downloadAudio()}><CloudDownload/>{t("profile.downloadYouTubeAudio")}</button></div>}
    {active&&download&&<div className="mt-3"><div className="flex items-center justify-between text-[9px] text-muted"><span>{download.message}</span><strong>{Math.round(download.progress)}%</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-raised"><i className="block h-full bg-accent transition-[width]" style={{width:`${Math.max(2,download.progress)}%`}}/></div></div>}
    {download?.status==="completed"&&<div className="mt-3 flex items-center gap-2 rounded-lg bg-success/10 p-3 text-[10px] text-success"><ShieldCheck className="size-4"/>{t("profile.youtubeAudioReady")}</div>}
    {error&&<div className="mt-3 rounded-lg bg-danger/10 p-3 text-[9px] text-danger">{error}</div>}
  </section>;
}
