import {useEffect,useRef,useState} from "react";
import {AlertTriangle,FileAudio,LoaderCircle,Mic,Plus,ShieldCheck,Square,Upload,X} from "lucide-react";
import {api} from "@/lib/api";
import {useI18n} from "@/i18n";
import type {VoiceboxPresetVoice,VoiceboxProfileInput} from "@/types";
type Props={onClose:()=>void;onCreated:()=>Promise<void>;initialType?:VoiceboxProfileInput["voice_type"]};
export function ProfileCreator({onClose,onCreated,initialType="preset"}:Props){
  const{t,locale}=useI18n();const[form,setForm]=useState<VoiceboxProfileInput>({name:"",language:locale,voice_type:initialType,preset_engine:initialType==="preset"?"kokoro":null,default_engine:initialType==="preset"?"kokoro":"qwen"});const[presets,setPresets]=useState<VoiceboxPresetVoice[]>([]);const[samplePath,setSamplePath]=useState("");const[referenceText,setReferenceText]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[recording,setRecording]=useState(false);const[recordingUrl,setRecordingUrl]=useState("");const[recordingData,setRecordingData]=useState("");const[recordingSeconds,setRecordingSeconds]=useState(0);const recorder=useRef<MediaRecorder|null>(null);const timer=useRef<ReturnType<typeof setInterval>|null>(null);
  useEffect(()=>{if(form.voice_type!=="preset"||!form.preset_engine){setPresets([]);return}api.voiceboxPresets(form.preset_engine).then(voices=>{setPresets(voices);if(voices.length)setForm(current=>({...current,preset_voice_id:current.preset_voice_id||voices[0].voice_id}))}).catch(reason=>setError(reason.message))},[form.voice_type,form.preset_engine]);
  useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);if(recordingUrl)URL.revokeObjectURL(recordingUrl);recorder.current?.stream.getTracks().forEach(track=>track.stop())},[recordingUrl]);
  const chooseSample=async()=>{const path=await window.dubStudio?.openAudio();if(path){setSamplePath(path);setRecordingData("");setRecordingUrl("")}};
  const startRecording=async()=>{try{setError("");const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const chunks:Blob[]=[];const mediaRecorder=new MediaRecorder(stream);recorder.current=mediaRecorder;mediaRecorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};mediaRecorder.onstop=()=>{const blob=new Blob(chunks,{type:mediaRecorder.mimeType||"audio/webm"});setRecordingUrl(URL.createObjectURL(blob));const reader=new FileReader();reader.onload=()=>setRecordingData(String(reader.result||""));reader.readAsDataURL(blob);stream.getTracks().forEach(track=>track.stop())};mediaRecorder.start(250);setRecordingSeconds(0);setRecording(true);timer.current=setInterval(()=>setRecordingSeconds(value=>value+1),1000)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}};
  const stopRecording=()=>{recorder.current?.stop();setRecording(false);if(timer.current)clearInterval(timer.current);timer.current=null};
  const save=async()=>{if(!form.name.trim()){setError(t("profile.nameError"));return}if(form.voice_type==="cloned"&&((!samplePath&&!recordingData)||!referenceText.trim())){setError(t("profile.referenceRequired"));return}setBusy(true);setError("");try{const profile=await api.createVoiceboxProfile(form);if(form.voice_type==="cloned"){if(recordingData)await api.addVoiceboxRecordingSample(profile.id,recordingData,referenceText.trim());else await api.addVoiceboxSample(profile.id,samplePath,referenceText.trim())}await onCreated()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
  return <div className="fixed inset-0 z-[100] flex justify-end bg-black/60 backdrop-blur-sm" onMouseDown={onClose}><aside className="grid h-full w-[520px] grid-rows-[64px_minmax(0,1fr)_64px] border-l border-line bg-surface shadow-2xl" onMouseDown={event=>event.stopPropagation()}><header className="flex items-center justify-between border-b border-line px-5"><div><span className="ui-kicker">{t("profile.workspace")}</span><h2 className="mt-1 text-[16px] font-semibold">{t("profile.new")}</h2></div><button className="ui-icon-button" onClick={onClose}><X/></button></header><section className="min-h-0 overflow-auto p-5"><div className="grid gap-4"><div className="grid grid-cols-2 gap-3"><Field label={t("profile.name")}><input autoFocus className="ui-input" value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder={t("profile.namePlaceholder")}/></Field><Field label={t("profile.language")}><select className="ui-input" value={form.language} onChange={event=>setForm({...form,language:event.target.value})}>{["fr","en","es","pt","de","ja","ko","zh","ar","it"].map(language=><option key={language} value={language}>{language.toUpperCase()}</option>)}</select></Field></div><Field label={t("profile.type")}><div className="grid grid-cols-3 gap-1 rounded-lg border border-line bg-canvas p-1">{(["preset","cloned","designed"] as const).map(type=><button key={type} className={`rounded-md px-2 py-2 text-[10px] ${form.voice_type===type?"bg-raised text-foreground":"text-muted"}`} onClick={()=>setForm({...form,voice_type:type,preset_engine:type==="preset"?"kokoro":null,default_engine:type==="preset"?"kokoro":"qwen"})}>{t(type==="cloned"?"profile.clone":type==="designed"?"profile.designed":"profile.preset")}</button>)}</div></Field>
    {form.voice_type==="preset"&&<div className="grid grid-cols-2 gap-3"><Field label={t("profile.engine")}><select className="ui-input" value={form.preset_engine||"kokoro"} onChange={event=>setForm({...form,preset_engine:event.target.value,default_engine:event.target.value,preset_voice_id:null})}><option value="kokoro">Kokoro</option><option value="qwen_custom_voice">Qwen CustomVoice</option></select></Field><Field label={t("profile.voice")}><select className="ui-input" value={form.preset_voice_id||""} onChange={event=>setForm({...form,preset_voice_id:event.target.value})}>{presets.map(voice=><option key={voice.voice_id} value={voice.voice_id}>{voice.name} · {voice.language?.toUpperCase()} · {voice.gender||"—"}</option>)}</select></Field></div>}
    {form.voice_type==="designed"&&<Field label={t("profile.description")}><textarea className="ui-input min-h-28" value={form.design_prompt||""} onChange={event=>setForm({...form,design_prompt:event.target.value})} placeholder={t("profile.descriptionPlaceholder")}/></Field>}
    {form.voice_type==="cloned"&&<div className="grid gap-3"><div className="flex gap-2 rounded-lg border border-success/25 bg-success/5 p-3 text-[10px] text-copy"><ShieldCheck className="size-4 text-success"/>{t("profile.cloneWarning")}</div><div className={`ui-panel p-5 text-center ${recording?"border-danger":""}`}><div className="mx-auto mb-4 flex h-12 items-center justify-center gap-1">{Array.from({length:30},(_,index)=><i key={index} className={`w-0.5 rounded ${recording?"animate-pulse bg-danger":"bg-accent/50"}`} style={{height:8+((index*11)%36)}}/>)}</div><strong className="text-[12px]">{recording?t("profile.recording"):recordingUrl?t("profile.captureReady"):t("profile.capturePrompt")}</strong><small className="mt-1 block text-[10px] text-muted">{recording?formatTime(recordingSeconds):t("profile.captureBody")}</small><div className="mt-4 flex justify-center gap-2">{recording?<button className="ui-button border-danger text-danger" onClick={stopRecording}><Square/>{t("profile.stop")}</button>:<button className="ui-button" onClick={()=>void startRecording()}><Mic/>{t("profile.record")}</button>}<button className="ui-button" onClick={()=>void chooseSample()}><Upload/>{t("profile.importSample")}</button></div>{recordingUrl&&<audio className="mt-4 h-9 w-full" src={recordingUrl} controls/>}</div>{samplePath&&<div className="flex items-center gap-2 rounded-lg border border-line bg-raised p-3 text-[10px]"><FileAudio className="size-4 text-accent"/><span className="truncate">{samplePath.split(/[\\/]/).pop()}</span></div>}<Field label={t("profile.referencePrompt")}><textarea className="ui-input min-h-24" value={referenceText} onChange={event=>setReferenceText(event.target.value)} placeholder={t("profile.referencePlaceholder")}/></Field></div>}
    <Field label={t("profile.personality")}><textarea className="ui-input min-h-20" value={form.personality||""} onChange={event=>setForm({...form,personality:event.target.value})} placeholder={t("profile.personalityPlaceholder")}/></Field>{error&&<div className="flex gap-2 rounded-lg bg-danger/10 p-3 text-[10px] text-danger"><AlertTriangle className="size-4"/>{error}</div>}</div></section><footer className="flex items-center justify-end gap-2 border-t border-line px-5"><button className="ui-button" onClick={onClose}>{t("profile.cancel")}</button><button className="ui-button ui-button-primary" disabled={busy||recording||!form.name.trim()||(form.voice_type==="preset"&&!form.preset_voice_id)} onClick={()=>void save()}>{busy?<LoaderCircle className="animate-spin"/>:<Plus/>}{t("profile.create")}</button></footer></aside></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5"><span className="ui-label">{label}</span>{children}</label>}
function formatTime(seconds:number){return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
